### ISSUE TITLE
With port 4243 of the Docker daemon enabled — compute_graph failure

### ISSUE THREAD

**Issue by preillyme** [google/cluster-insight#61] opened 2015-05-23 01:18 UTC
Seeing the following error:
```
{
  "error_message": "compute_graph(\"context_graph\") failed with exception <type 'exceptions.AssertionError'>", 
  "success": false, 
  "timestamp": "2015-05-23T02:45:15.784381"
}
``` 
while accessing: ```http://127.0.0.1:5555/cluster```

I'm testing with: ```sudo docker run -d --net=host -p 5555:5555 --name cluster-insight kubernetes/cluster-insight python ./collector.py --debug```

Manually accessing: ```http://127.0.0.1:8080/api/v1beta3/nodes``` returns:
```
{
  "kind": "NodeList",
  "apiVersion": "v1beta3",
  "metadata": {
    "selfLink": "/api/v1beta3/nodes",
    "resourceVersion": "52"
  },
  "items": [
    {
      "metadata": {
        "name": "127.0.0.1",
        "selfLink": "/api/v1beta3/nodes/127.0.0.1",
        "uid": "05c3c93b-00f5-11e5-9399-000c291c504f",
        "resourceVersion": "52",
        "creationTimestamp": "2015-05-23T02:40:06Z",
        "labels": {
          "kubernetes.io/hostname": "127.0.0.1"
        }
      },
      "spec": {
        "externalID": "127.0.0.1"
      },
      "status": {
        "capacity": {
          "cpu": "2",
          "memory": "2042388Ki",
          "pods": "100"
        },
        "conditions": [
          {
            "type": "Ready",
            "status": "True",
            "lastHeartbeatTime": "2015-05-23T02:44:47Z",
            "lastTransitionTime": "2015-05-23T02:40:06Z",
            "reason": "kubelet is posting ready status"
          }
        ],
        "addresses": [
          {
            "type": "LegacyHostIP",
            "address": "127.0.0.1"
          }
        ],
        "nodeInfo": {
          "machineID": "48c3ef3692591b8704551c0854a71263",
          "systemUUID": "564D95DE-D9A6-6364-2B0A-8CC30A1C504F",
          "bootID": "b64febb8-f82b-4e94-9e6c-f3c4d280c6d5",
          "kernelVersion": "3.13.0-51-generic",
          "osImage": "Ubuntu 14.04.2 LTS",
          "containerRuntimeVersion": "docker://1.6.0",
          "kubeletVersion": "v0.17.1-731-g4292866c031fb7",
          "kubeProxyVersion": "v0.17.1-731-g4292866c031fb7"
        }
      }
    }
  ]
}
```

**Comment by preillyme** [comment] 2015-05-23 01:43
e.g., can't you just do something like: ```sudo docker run -d --net=host -p 5555:5555 -p 4243:4243 --name cluster-insight kubernetes/cluster-insight python ./collector.py --debug```

**Comment by preillyme** [comment] 2015-05-23 03:03
It's worth noting that I'm running my kubernetes cluster with: ```./hack/local-up-cluster.sh``` which might actually be the reason for the failure.

**Comment by EranGabber** [comment] 2015-05-29 19:00
I just pushed the support for v1beta3. I did not push a new binary yet to Docker Hub. Please recompile the cluster insight collector from the latest source and retry.

**Comment by EranGabber** [comment] 2015-06-01 20:51
v1beta3 support is now complete. Could you compile the Cluster Insight collector from the latest sources and retry?

**Comment by EranGabber** [comment] 2015-06-23 15:21
I am closing this issue. I assume that the new master/minion architecture resolved this issue already. Please feel free to reopen if the problem is not completely solved.

**Closed by EranGabber** 2015-06-23 15:21 UTC
